name: 'Checkout, Setup, Node, Yarn Install'
author: 'Brian Espinosa'
description: 'Composite action that will check out our code, set up node and yarn with caching, and install yarn dependencies'

branding:
  icon: 'download-cloud'
  color: 'green'

runs:
  using: "composite"

  steps:
    # https://github.com/actions/checkout#usage
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # https://github.com/actions/setup-node#usage
    # NOTE: Due to a long-standing problem with this action not having support for corepack, we need to:
    #       1. Install node first
    #       2. Enable Corepack
    #       3. Enable dependency cache
    #       https://github.com/actions/setup-node/issues/531
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Enable dependency cache
      uses: actions/setup-node@v4
      with:
        cache: "yarn"
        cache-dependency-path: |
          **/*.lock
          yarn.lock

    - run: yarn install --immutable
      shell: bash
      
